[CE_Cyclactions]
Nb_Actions=0
Version=3

[Cyclactions]
; Do not tweak by hand! Use the Cycle Action editor instead ===
Version=3

[Main_Cyclactions]
Action1=Dark/Light Mode Switch|_S&M_LOAD_THEME1|!|_S&M_LOAD_THEME2|
Nb_Actions=1
Version=3

[MainAlt_Cyclactions]
Nb_Actions=0
Version=3

[ME_Inline_Cyclactions]
Nb_Actions=0
Version=3

[ME_List_Cyclactions]
Nb_Actions=0
Version=3

[ME_Piano_Cyclactions]
Nb_Actions=0
Version=3

[MediaEx_Cyclactions]
Nb_Actions=0
Version=3

