desc:Container Selector Expansion
author: saxmand
version: 1.0
noindex: true
changelog: Initial release

/**
 * JSFX : Button Modulator
 * Author: Jesper Ankarfeldt
 * Reaper forum : 
 * Licence: GPL v3
 * REAPER: 7.0
 * Version: 10 (2024-11-14)
 */

slider1:0<0,100,0.001>Selection
slider2:0<0,12,1>Used

slider3:1<0,1,1{Off ,On}>Toggle
slider4:1<0,1,1{Off ,On}>Select
slider5:0<0,1,1{Off ,On}>Fill

// Only used by the lua script
slider6:0<0,1,1{Off ,On}>Hide 


slider11:0<0,100,1>Selector 1
slider12:0<0,100,1>Selector 2
slider13:0<0,100,1>Selector 3
slider14:0<0,100,1>Selector 4
slider15:0<0,100,1>Selector 5
slider16:0<0,100,1>Selector 6
slider17:0<0,100,1>Selector 7
slider18:0<0,100,1>Selector 8
slider19:0<0,100,1>Selector 9
slider20:0<0,100,1>Selector 10
slider21:0<0,100,1>Selector 11
slider22:0<0,100,1>Selector 12

in_pin:none
out_pin:none

@slider

S    = floor(slider1*slider2+0.5);
tog  = slider3;
sel  = slider4;
fill = slider5;

i = 1;
loop(slider2,
    sel == 1 ? (
        tog == 1 ? 
        (fill == 0 && S >= (i-1)*100 + 1 && S <= i*100) || (fill == 1 && S >= (i-1)*100 + 1) ? 
            slider(i+10) = 100 : slider(i+10) = 0;//slider(i+10) = S - (i-1) * 100;
        
        tog == 0 ? 
        (fill == 0 && S >= (i-1)*100 + 1 && S <= i*100) || (fill == 1 && S >= (i-1)*100 + 1) ? 
            slider(i+10) = min(100, S - (i-1) * 100) : (
              S >= (i)*100 + 1 ? slider(i+10) = max(0,100 - (S - (i) * 100)) : slider(i+10) = 0;
              );
        
              
    
    );
    i += 1;
);
    
 
  
  
